[config]
schemaVersion = "0.0.1"

[package]
namespace = "GatekeeperModding"
name = "ExampleMod"
versionNumber = "1.0.0"
description = "ExampleMod"
websiteUrl = "https://github.com/GatekeeperModding/ExampleMod"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_IL2CPP = "6.0.733"
GatekeeperModding-GKAPI = "0.1.2"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = "./plugins/ExampleMod"

[publish]
repository = "https://thunderstore.io"
communities = ["gatekeeper"]
categories = ["mods"]